<Project>
  <PropertyGroup>
    <Authors>Pendragon Development</Authors>
    <Company>Pendragon Development</Company>
    <Product>Huddle</Product>
    <PackageIcon>icon.png</PackageIcon>
    <Copyright>Copyright 2026 Pendragon Development</Copyright>
    <VersionPrefix>0.9.0</VersionPrefix>
    <PackageProjectUrl>https://github.com/davewheatcroft3/Huddle</PackageProjectUrl>
    <RepositoryUrl>https://github.com/davewheatcroft3/Huddle</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageReleaseNotes>Initial release.</PackageReleaseNotes>
    <PackageTags>dotnet;maui;networking;local-network;service-discovery;peer-to-peer</PackageTags>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
    <DebugType>portable</DebugType>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
  </PropertyGroup>

  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)..\NOTICE" Pack="true" PackagePath="\" Visible="false" />
    <None Include="$(MSBuildThisFileDirectory)..\images\icon.png" Pack="true" PackagePath="\" Visible="false" />
  </ItemGroup>
</Project>
